### ISSUE TITLE
web module error

### ISSUE THREAD

**Issue by pankk** [OCA/OpenUpgrade#107]
Hi,

I'm getting an error (see below) when using an upgraded database upgraded using the c1b9ad1 commit. I think I'm using the wrong (too new) revision of Odoo. I've tried multiple revisions of Odoo:
4f5cc004: as mentioned at https://github.com/OpenUpgrade/OpenUpgrade/pull/1 but this seems dated and gives me an error on report/modules/report.py; 
932ecccc: (Odoo 8.0) initially gives a ir_ui_view.action does not exist error but works after an update all, but I get a javascript web module error; 
e4521e4 (older Odoo 8.0): works without the update all but I get the same web error). 
Which revision of Odoo should I use?

The error I'm getting:
From sales->customers in kanban view click on a partner pops up:
Uncaught TypeError: Cannot read property 'constructor' of undefined
http://0.0.0.0:8068/web/js/web.assets_backend/ce41694:2840
(found this in addons/web/static/lib/src/js/pyeval.js around line 719)

and:

Uncaught Error: QWeb2 - template['FieldRadio']: Runtime Error: TypeError: Cannot read property '1' of undefined
http://0.0.0.0:8068/web/js/web.assets_common/08701fd:1020
(found this in addons/web/static/lib/qweb/qweb2.js around line 48

**Comment by pankk** [comment]
This problem is solved by migrating mail.

**Comment by martintamare** [comment]
Could you elaborate on how to solve the problem ?

**Comment by pankk** [comment]
@martintamare IIRC the mail module did not have migration scripts at the moment of opening this issue, they were added a few weeks later, so you should not run into the same issue as above anymore using a recent version of OpenUpgrade. Have a look at the mail migration scripts, they might hold a clue to solving the errors you are getting.

**Comment by martintamare** [comment]
Here is what fixed the issue for me using raw postgresql (ugly but efficient ^^):
`update res_partner set  notify_email ='always' where notify_email='none';`

The problem was present when clicking on a res.partners in the list view -> I then focus on the res.partner table and see the constraint there. none was not supposed to be in notify_email :)

**Comment by pankk** [comment]
@martintamare Thanks for sharing your solution. Maybe I don't fully understand the problem, and I'm not sure to which version you are migrating, but 'none' should be a valid option for that field (e.g. [https://github.com/odoo/odoo/blob/master/addons/mail/models/res_partner.py#L21](url)).

**Comment by martintamare** [comment]
We started with openrp 7.0 then updating to odoo 8.0 using OCA.
Since the migration, we had this issue. Debugging the JS is a real pain so maybe that is not the correct fix. 
We had a dirty installation with plenty of old module, I clean it all, let's see where this is leading us ;)
Anyway I can't reproduce the issue anymore, so ... :)

**Comment by alesisjoan** [comment]
Had a similar problem migrating 7.0 to 8.0.

The field notification_email_send is 'comment' while 8.0 accepts as 'always'.
