### ISSUE TITLE
How to contribute to OpenUpgrade migration scripts

### ISSUE THREAD

**Issue by erkesado** [OCA/OpenUpgrade#1167]
I have enough experience in Odoo module development.
I further would like to contribute in OpenUpgrade development.
But I can't figure out where to start from. I can't even figure out how to run OpenUpgrade migration even though I went through OpenUpgrade documentation (https://doc.therp.nl/openupgrade).
Have you guys experienced this when you were a novice like me?
How did you manage to overcome this barrier (insufficient documentation)?
Could you please share your experiences? Where did you start from? How did you manage to run OpenUpgrade migration?

**Comment by legalsylvain** [comment]
Hi @erkesado, 

Well basically, openupgrading a database is simply run an --update all on a database.

simple example : 
If your database is 8.0 and you want to migrate in 9.0 for exemple. You have to : 
- get all your code for the 9.0 version. (OCA modules, Custom modules, ...)
- replace your Odoo project by the OCA/OpenUpgrade project for the version 9.0.)

- Make sure that all your code works on version 9.0.
- run the command with the following args : --update all --d my_database.

If all the migration is OK (no blocking error), then it's a good news ! And you can test your new instance.

Otherwise, 
- either your 8.0 database was corrupted, so you have to fix your 8.0 database (by SQL script for exemple) and rerun the migration
- or your 8.0 database is OK, and so you have to write a script in a migration folder of OpenUpgrade project, and make a PR.

What is your precise needs ?

regards.

**Comment by erkesado** [comment]
Thanks for your answer, @legalsylvain.
I have odoo 9.0 databases and need to migrate to odoo 10.0.
After 9.0 to 10.0 migration, I also need to migrate to 11.0.
To migrate to 11.0 as soon as possible, I would like to contribute to OpenUpgrade development.
I see that your answer is enough to run OpenUpgrade for core modules and play with it.
Thanks again.

**Comment by erkesado** [comment]
I have managed to successfully run Odoo 9.0 to Odoo 10.0 migration with OpenUpgrade.
Thanks again for your comment, @legalsylvain.
