### ISSUE TITLE
Migration from 9.0 to 11.0

### ISSUE THREAD

**Issue by abuerto** [OCA/OpenUpgrade#1242]
Impacted versions: I need to migrate 9.0 to 11.0

Steps to reproduce: Due to the documention is not very clear it have been so difficult to use the OpenUpgrade, finally I could be able to complete the migration instaling openupgradelib and running the migrate.py

Current behavior: The migration was executed without any error, but what is next? How I use the files created by migrate.py to complete the migration process? Where I can find a step by step guide or instructions?

Expected behavior:

Video/Screenshot link (optional):

**Comment by pedrobaeza** [comment]
Steps are simple:

- Update all addons with OpenUpgrade n+1 version
- Use migrated DB with Odoo n+1 version.

**Comment by abuerto** [comment]
Thanks for your response Pedro, I did that but the migrated DB have only a few tables, around 120 and original more than 400, there's are a lot of missing data and the migration.log do not shows errors

**Comment by pedrobaeza** [comment]
You have to migrate to 10.0 first, and then to 11.0, but the problem is that OpenUpgrade 11.0 is still far from complete. Please check module coverage.

**Comment by abuerto** [comment]
Ohh ok I understand, thanks!!

**Comment by abuerto** [comment]
Pedro, I did tha migration only from 9.0 to 10.0 and is the same, there are just a few tables, 9.0 DB 435 tables and migrated 10.0 DB 105 tables. How can I migrate only database from one version to another??

**Comment by pedrobaeza** [comment]
But that doesn't make sense. OpenUpgrade doesn't remove tables. I think you are not taking the original DB as source.

**Comment by DonFeraRRi** [comment]
Hi abuerto I was going through your details, I just needed to know few things. Due to lack of proper documentation, I am facing certain issues. 
What I want is, to Migrate my 9 database to 10. I downloaded UpenUpgrade10 as its defined as OpenUpgrade n+1. I tried Running it manually by replacing my odoo folder and selecting OpenU0pgrade. But my database after login screen where I eneter my credentials, it throws an error.
Could you please let me know where I was wrong and what I need to do.
