### ISSUE TITLE
[9.0] 8 to 9, account_analytic_analysis, "could not get content for (...).css in bundle 'web.assets_backend'"

### ISSUE THREAD

**Issue by dreispt** [OCA/OpenUpgrade#1425]
The `account_analytic_analysis`was removed in 9.0, and #400 says "nothing to do".
But there are module "leftovers" in the database, and [one in particular](https://github.com/odoo/odoo/blob/8.0/addons/account_analytic_analysis/views/account_analytic_analysis.xml) causes this css issue, preventing the web client to load correctly.

Should this be properly handled buy some migration script (maybe in `analytic`)?

**Comment by pedrobaeza** [comment]
No, you should uninstall the module (that will be found now as `contract` due to https://github.com/OCA/OpenUpgrade/blob/9.0/openerp/addons/openupgrade_records/lib/apriori.py#L44), or put in your module list that module and everything will be fine thanks to these migration scripts: https://github.com/OCA/contract/tree/9.0/contract/migrations/9.0.1.0.0

**Comment by pedrobaeza** [comment]
Said this, documentation can be improved.

**Comment by dvrles001** [comment]
Can anyone point me in the right direction on how to manually remove this module?
