### ISSUE TITLE
8 to 9: move lines with tax_code_id but no tax_line_id nor tax_ids

### ISSUE THREAD

**Issue by sbidoul** [OCA/OpenUpgrade#1436]
Impacted versions:

8 to 9

Steps to reproduce:

Investigating. After migration, there are move lines where both tax_line_id and tax_ids are not set, but have a tax_code_id.

Current behavior:

The following query lists problematic move lines.

```sql
select aml.id 
from account_move_line aml 
left join account_move am on am.id = aml.move_id 
where 
  tax_code_id is not null and 
  (tax_line_id is null and 
   not exists (
        select * from account_move_line_account_tax_rel 
        where account_move_line_id=aml.id)
   );

**Comment by StefanRijnhart** [comment]
The current code was made based on databases with the Spanish localization and does not work for the Dutch localization either. I created https://github.com/OCA/OpenUpgrade/pull/1172 for that. Do you think that PR's approach would give you a better result?

**Comment by jonerikceberio** [comment]
Confirmed here, Spanish localization with duplicated taxes (Vat included and Vat excluded). 
My two cents: Instead of trying to match tax codes with taxes, how about going back to the origin of the move? E.g. going back to the invoice to get the tax from there.
`update account_invoice_tax ait
set tax_id=aix.id
from account_invoice ai
		inner join (
			select ail.invoice_id as invoice_id,
				at.tax_code_id as tax_code_id,
				at.id as id
			from account_invoice_line ail
				inner join account_invoice_line_tax ailt on ailt.invoice_line_id=ail.id
					inner join account_tax at on ailt.tax_id=at.id and at.tax_code_id is not Null --and at.active=True
			group by ail.invoice_id,at.tax_code_id,at.id
		) aix on aix.invoice_id=ai.id
where ait.invoice_id=ai.id
	and aix.tax_code_id=ait.tax_code_id
	and ait.tax_id is Null`


`update account_move_line aml
set tax_line_id=ait.tax_id
from account_invoice ai
		inner join account_invoice_tax ait on ait.invoice_id=ai.id
	, account_account aa
where aml.invoice_id=ai.id 
	and aml.account_id=aa.id
	and (aa.code ilike '472%'
		or aa.code ilike '477%'
		or aa.code ilike '470%')
	and (ait.amount=aml.credit
		or ait.amount=aml.debit)
	and aml.tax_line_id is Null`

Or updating from pos order
`update account_move_line aml
set tax_line_id=pot.tax
from account_move am 
		inner join pos_order po on po.account_move=am.id
			inner join pos_order_tax pot on pot.pos_order=po.id
	, account_account aa
where aml.move_id=am.id 
	and aml.account_id=aa.id
	and (aa.code ilike '472%'
		or aa.code ilike '477%'
		or aa.code ilike '470%')
	and pot.amount=aml.credit
	and aml.tax_line_id is Null`

I have seen about three variants of pos.order and account.invoice origins, depending on the data, but launching several sqls should solve the problem.

**Comment by pedrobaeza** [comment]
Well, that can be a refinement indeed, but not easy on SQL and scalable for a lot of data. If you want to try a PR, it would be very welcome.

**Comment by pedrobaeza** [comment]
Any way, take into account that the first problem you have is that there's no trace from account.move.line to account.invoice.line, so the tax is not easy to be guessed.

**Comment by sbidoul** [comment]
FWIW, we finished testing https://github.com/OCA/OpenUpgrade/pull/1432. 

We finally gave up trying to reuse existing taxes on move lines, so we create inactive taxes for the sole purpose of preserving the exact same vat declaration for migrated moves.

**Comment by pedrobaeza** [comment]
Closing this as already discussed.
