### ISSUE TITLE
less files not loaded after database upgration from v8 -> v11

### ISSUE THREAD

**Issue by twe-t** [OCA/OpenUpgrade#1504]
I have migrated a database with openupgrade v8 -> v11.
Then run the database with  odoo community v11 instance with -u all command.
Migration is successfull but it looks like less files does not loaded at the time of start the odoo instance.
Note: [Migrated DB size: 6 GB approx; ]
Please check the image traceback pop up at backend.

Current behavior: Could not able to access odoo instance. 

Expected behavior: Odoo instance should be accessible.

Video/Screenshot link (optional):
![11111](https://user-images.githubusercontent.com/28892620/44907607-2b3c2000-ad36-11e8-864d-6c968af6624d.png)

**Comment by pedrobaeza** [comment]
Have you migrated directly from v8 to v11? You have to migrate first to v9, then to v10 and then to v11.

**Comment by twe-t** [comment]
@pedrobaeza Thanks for quick reply.
Yes I had migrate through all the concurrent versions one by one.

**Comment by pedrobaeza** [comment]
But there are a lot of reasons why this happens, and not being OpenUpgrade guilty. First, you need to check full stack trace. This usually happens because website standard pages are marked with noupdate="1" because they have been manually modified through CMS. You have to remove that flag and update again.

Any way, without more information, it's impossible to help.

**Comment by pedrobaeza** [comment]
Closing as no further news.
