### ISSUE TITLE
[12.0] base module migration: admin id

### ISSUE THREAD

**Issue by hmrodrigues** [OCA/OpenUpgrade#1536]
I've a question regarding the base model migration.

How will we handle the admin user id?
In Odoo 12, the admin user now has the ID 2 and the root user (aka System) has the ID 1

I believe that the root user (ID 1) will not be a problem (the role is the same, but now has a different name and can't login (unable to set active=True, at least via ORM), but the admin user (now with id 2) can be, because the new admin will be a old normal user (or even a public one)

An example for this is the flow to set the [web.base.url](https://github.com/odoo/odoo/blob/12.0/odoo/addons/base/models/res_users.py#L581) parameter. If a module implements something like this but without a try except block, the user will have issues with permissions.

**Comment by StefanRijnhart** [comment]
Thank you so much for noting the hardcode admin user id when setting the web.base.url parameter. I had not seen this, and in my base migration PR I am creating the admin user as a copy of the superuser (see
https://github.com/OCA/OpenUpgrade/pull/1531/files#diff-dc09a830b46c834278b85d839da79ba1R8).

If Odoo insists on keeping the static id we would need to move the existing user with ID 2 and it would be a lot slower because we'd need to lift all foreign key constraints on res users (at least two on most tables, namely create_uid and write_uid), swap the ids around and readd the foreign key constraints. I'd rather not do that, and I'm guessing the Odoo migration script developer does not want to do that either and I'm hoping the Odoo core developers will agree with me that hardcoded ids are plain stupid so I'm giving it a go in this PR: https://github.com/odoo/odoo/pull/27432/files

**Comment by hmrodrigues** [comment]
@StefanRijnhart I agree with you with the hardcoded ids. Lets hope that they agree with us and the PR gets accepted.

**Comment by StefanRijnhart** [comment]
Looks like upstream is willing to go this way. So I think we can close this issue if your question is answered.
