### ISSUE TITLE
[7->8] Strategy for disapeared modules ?

### ISSUE THREAD

**Issue by legalsylvain** [OCA/OpenUpgrade#155]
Hi all, 
I have maybe a lead to realize in a few month a migration 7-> 8. During the analysis, I saw that there was 5 modules that was present in V7 and had disapeared in V8: 
document_ftp, mrp_jit, process, stock_location, stock_no_autopicking,

Do you know if there is some OCA modules that replace them ?
Did you faced to the same problem ?
(For example, I saw that web_shortcuts has moved from Odoo to OCA / web)

Regards.

**Comment by hbrunn** [comment]
mrp_jit is procurement_jit now. No good ideas about the rest though

**Comment by pedrobaeza** [comment]
These are my comments about the missing modules:
- document_ftp: This module was very buggy and was isolated in a branch (https://code.launchpad.net/~openerp-community/openerp-extra/8.0-document) that I don't know if still works with current v8. Somebody might take care of updating it and putting on OCA knowledge repo.
- process: This seems redundant for Fabien Pinckaers with current workflow, which is not accurate, but the module has dissapeared. As this is only used for information, there is no impact in its removal, but somebody can also rescue it for OCA, migrating to v8.
- stock_location: This logic is already included in WMS new stock module, so it's no longer needed.
- stock_no_autopicking: This module is no longer needed, because now mrp doesn't create a picking for preparing raw materials. This is done via routes. You should reconfigure migrated DB routes for mimicking the same logic.

**Comment by StefanRijnhart** [comment]
Acsone have ported web_shortcuts to 8.0: merged in https://github.com/OCA/web/pull/56. BTW taking care of clean migration to procurement_jit in #177

**Comment by legalsylvain** [comment]
OK. I wrote a little page in the wiki that sums up this discussion. 
https://github.com/OpenUpgrade/OpenUpgrade/wiki/Migration-from-7.0-to-8.0
You can update it.
+++

**Comment by StefanRijnhart** [comment]
Thanks. Comments added.
