### ISSUE TITLE
[8.0] product: image_variant

### ISSUE THREAD

**Issue by pablocm-aserti** [OCA/OpenUpgrade#166]
Hello

I'm trying to upgrade from 7 to 8, but when it reaches [here](https://github.com/OpenUpgrade/OpenUpgrade/blob/8c5581dab3535f3e322f660af0249321017b925b/addons/product/migrations/8.0.1.1/post-migration.py#L132-L136) I get an error.
Why is it trying to move image_variant from product.product to product.template if it is a new field in 8.0 and there is nothing to do according to [this](https://github.com/OpenUpgrade/OpenUpgrade/blob/8c5581dab3535f3e322f660af0249321017b925b/addons/product/migrations/8.0.1.1/openupgrade_analysis_WORK.txt#L63-L64)?
Shouldn't it be [image](https://github.com/OpenUpgrade/OpenUpgrade/blob/8c5581dab3535f3e322f660af0249321017b925b/addons/product/migrations/8.0.1.1/openupgrade_analysis_WORK.txt#L59-L61)?

**Comment by pedrobaeza** [comment]
Hi, Pablo, in pre-script, field image has been renamed to image_variant (https://github.com/OpenUpgrade/OpenUpgrade/blob/8.0/addons/product/migrations/8.0.1.1/pre-migration.py#L30), so the instruction is correct. What it does is to copy the image to the template, because previously, it was only on the product.

**Comment by pablocm-aserti** [comment]
Thanks Pedro!

I'll further investigate the problem then, because once I commented the lines and re-run the upgrade, it passed that part and uncommenting again gave no problems. There must be something wrong on my side.

Sorry to bother and thanks again.
