### ISSUE TITLE
[Discuss] patch distribution of OU

### ISSUE THREAD

**Issue by lina2358** [OCA/OpenUpgrade#1667]
We have had promising results with maintaining a [patch distribution](https://github.com/xoe-labs/odoo-dev) (see branches) of Odoo with the help of some [special purpose git tooling](https://github.com/xoe-labs/dockery-odoo-scaffold/blob/master/hack/odoo-dev.py).

Given the case that OU _could_ be distributed as a set of patches, it would be easier to adopt in custom code bases.

**Comment by pedrobaeza** [comment]
I don't get the advantages of that. It's more difficult to maintain and no need to be adopted by any custom code base IMO. You use OpenUpgrade for migrating between versions, and openupgradelib to make some migration tasks inside same version or in OpenUpgrade. What more do you need?

**Comment by lina2358** [comment]
@pedrobaeza thanks for your reply. I see it as an _alternative_. To me it _seems_ advantageous. I don't understand "no need to be adopted by any custom code base".

What I had in mind: I could do `git pull openupgrade compiled/12` and my current code base state would be "topped up" to become an open upgrade one.

As I understood it OU _is_ already a set of patches in reality, it is just not _distributed_ as one.

Am I misunderstanding something?

**Comment by pedrobaeza** [comment]
Then you are promoting an alternative in this repository?

**Comment by lina2358** [comment]
@pedrobaeza I'm not sure if we can speak really of "promoting", it's just an idea I deemed worth sharing and discussing. Of course the idea comes with a line of thought, and but not with an agenda.

**Comment by pedrobaeza** [comment]
Then please propose specific actions to do in current repository, and we can discuss.

**Comment by lina2358** [comment]
@pedrobaeza: How would proposal "rebase and connect to Odoo git history" sound like? After all I think that's all that's needed to support the proposed use case.

Or is that already the case? It's not obvious as this repository is not a fork of Odoo.

**Comment by pedrobaeza** [comment]
We do this regularly, but on OpenUpgrade itself, see for example: https://github.com/OCA/OpenUpgrade/pull/1621

**Comment by lina2358** [comment]
@pedrobaeza Almost. You _merge_ upstream odoo. You don't _rebase_ Openupgrade patches upon upstream Odoo. If so, it would be trivial to apply OU on a custom code base. Or do I misunderstand something?

**Comment by lina2358** [comment]
Also, I have to note that using git `rerere` (and share it among maintainers) makes conflict resolution orthogonal to irrelevant code changes. It is an extremely streamlined workflow. And if something breaks you would be auto hinted by a rerere breakage. Different aspects of the OU can be maintained on different topic branches (modularity) and compiled into a synthetic distro branch aka `compiled/12`

**Comment by pedrobaeza** [comment]
@acl2358 you are starting to sound more and more like @blaggacao, not being understandable and going to abstract concepts that no one except you want and understand. Several points from what I think I understand:

- If you patch your Odoo core, you are doing something bad, as a modular system like this one is not for patching it.
- We don't want light libraries for migrating, as we are taking advantage of all the features included in Odoo and its upgrade mechanism. Re-doing that work simply doesn't make sense. And why reinventing the wheel any way?
- OpenUpgrade allows modularity, as you can include migration script for any module (in OCA there are a lot, for example, in OCA/bank-payment 9.0 branch).

**Comment by blaggacao** [comment]
@pedrobaeza Hehe, might be because we have a chance to discuss things in person, but it seems still to be the most effective means of communication, indeed. 

If you want to stop this discussion, please just say it. I feel frases convoking majority pressure assumptions like "no one except you" are neither a fair or nor efficient way to convert this into a fruitful discussion.

If an argument is not clear for me, then I might want to refrain as much as I can from forming a canned opinion. 

How does your answer relate to providing a patch branch to distribute OU?

I think, materially, it's a completely ortogonal answer. 

I feel again and again that any (interesting) discussion gets cloaked in an "opinion filter bubble". 😔

**Comment by pedrobaeza** [comment]
@blaggacao I'm giving you facts for saying that I don't see this interesting, and I'm not the only one that doesn't understand your arguments as he recently told to you directly, so if 2 of the most prominent maintainers of this project says something similar, and the rest even don't waste time answering, don't you think this is more than an opinion filter bubble?

As I have tried other times to transmit to you, this is not something personal, on contrary as you have expressed to my person in Twitter, only that it's not needed to reinvent the wheel each time, as you pretend to do since you arrived in the Odoo ecosystem. You can have great ideas - you have already contributed with some of them very good -, but that ideas should be very well guided for leading to a "material goal", so I repeat my advises that I gave you in other issue for achieving something in an open source community:

- Don't elaborate everything too much. It's not needed and this makes possible reviewers reluctant.
- Sort your ideas before writing, and then write them. Don't post 4-5 concatenated messages, each one rephrasing the same and going around.
- As said, don't try to reinvent the wheel. In this project, OpenUpgrade has served for migrating all kind of Odoo installations from v5 to v11 (and soon v12), and that's because is very good in its purpose, so no need to reinvent it. Everything has space for improvement, of course, but tirst rule of any ecosystem consists in respecting their paradigms. Patching a distribution means to not respect the modular paradigm.
- Most of the open source communities are meritocracy, and due to very strong reasons. When you'll have a considerable amount of PRs here in OpenUpgrade, following current paradigm for knowing well enough what is going on, then people can consider your discussions for changing the paradigm viable because of your deep knowledge of it. Meanwhile, it can be considered just ignorance of it (I'm not saying that you are ignorant about the topic - just that you haven't proved it  -).
- And finally, use other redaction style, not using elaborated words in Spanish literally translated to English. Plain English acts better than trying to be "Góngora" without being native speaking.

**Comment by blaggacao** [comment]
I understand everything you say and I've to say I appreciate it.

_If you (or anybody) sometimes ask yourself: What is this guy up to?_ 

**The answer is:** 
_I'm just projecting my vision, not power. (So nobody ought to feel offended)_

I hope for this vision to gain traction and power and finally materialize to the benefit who might want to rejoice it. And I honestly have little compassion for the _merits of meritocracy_. It seems like with vitamins/poisons: 

- too little kills you
- too much kills you
