### ISSUE TITLE
[8-9] Fields not migred

### ISSUE THREAD

**Issue by CarlesAntoli** [OCA/OpenUpgrade#1796]
**Impacted versions:** 9.0

**Steps to reproduce:**
Migrate a database in v8

**Current behavior:**

The data in "base" field of the account.invoice.tax object does not migrate, the values are 0.

In object pos.order.line in the field "tax_ids_after_fiscal_position" the taxes are not migrated, they appear empty.

![pos](https://user-images.githubusercontent.com/9009418/56144066-f5d10380-5fa1-11e9-802c-721f44117426.jpg)
![factura](https://user-images.githubusercontent.com/9009418/56144070-f9fd2100-5fa1-11e9-8acc-9cf0deafe887.jpg)

**Comment by pedrobaeza** [comment]
That's because the heuristic for detecting which tax matches with that account.invoice.tax has failed. This usually happens when you have updated the CoA and there's no correspondence of the tax name with current taxes. If you find another heuristic for matching this, a PR is welcome, but meanwhile, there's better solution, so closing.

P.S: Data structure in v8 was so bad that nothing better can be done except heuristics.
