### ISSUE TITLE
[12.0] uom: _check_category_reference_uniqueness

### ISSUE THREAD

**Issue by MiquelRForgeFlow** [OCA/OpenUpgrade#1914]
The `_check_category_reference_uniqueness` method is a constraint [added](https://github.com/odoo/odoo/commit/e0ed50a724eb129451d98d93e7365b4b117cfd0a) in v12, that forces the existence of only one UoM reference per category.

So, in the migration of uom module, this constraint is checked. What should we do with the data in case it raises any of its validation errors? 🤔

**Comment by pedrobaeza** [comment]
I think we shouldn't do anything special: that condition would make your DB to fail in certain flows even in previous versions, so it's something that must be fixed ASAP. We can't decide which UoM must be the reference one, so if the migration fails due to this, then you know that you must repair this before migration.

**Comment by fescon** [comment]
Maybe I oversee something - following case - during inital setup the reference between day and hour was changed because customer wanted hours as reference uom. Now upgrade fails while reading data.xml in uom. Any suggestions?
Thanks a lot!

**Comment by pedrobaeza** [comment]
You have to switch before migrating.
