### ISSUE TITLE
[11.0][STOCK] Missing serial numbers in stock.move.line

### ISSUE THREAD

**Issue by OthmaneGhandi** [OCA/OpenUpgrade#2000]
Impacted versions:

Steps to reproduce:

In outgoing deliveries in V10: you find that n P1 was delivered and the serial numbers were listed in pack_lot_ids **(stock.pack.operation.lot)**

But in V11 : you only have the whole quantity is delivered without any details about the serial numbers of the product in **(stock.move.line)**

@pedrobaeza Thank you for your continued support

**Comment by pedrobaeza** [comment]
This is covered for most cases, so you have to dig a bit more what is the weird case where the lot is not transferred to stock.move.line.

**Comment by OthmaneGhandi** [comment]
@pedrobaeza 
It occurs for me for moves in **done** state.
In **post-migration.py** -> **create_stock_move_line** : you are using data from **stock_pack_operation** and I didn't see a JOIN with **stock_pack_operation_lot** is it normal ?

Am I missing something ?

**Comment by pedrobaeza** [comment]
Lot information is taken from the quant linked to the stock.pack.operation:

https://github.com/OCA/OpenUpgrade/blob/29acc14cee567c597436cc4cbced6c9119c45741/addons/stock/migrations/11.0.1.1/post-migration.py#L198

`stock.pack.operation.lot` table can't be used as it changes cardinality of the SQL, provoking bad sumed quantities. More info in the commit description in https://github.com/OCA/OpenUpgrade/commit/91bba0cf0f4aac58ff812f59f38d7ea28eda7634#diff-fe7bbc3631adade92da541853a857311.

Check why don't you have `reserved_quant_id` filled in stock.move.operation.link.

**Comment by OthmaneGhandi** [comment]
@pedrobaeza Indeed the `reserved_quant_id` is not filled, do you think that is something related to only my database ?

we can't have cases where `reserved_quant_id` is empty and still have serial numbers ?

I didn't see when this field get filled

**Comment by pedrobaeza** [comment]
Maybe your DB was using outdated code (or are you coming from <v10?).

It's filled here:

https://github.com/odoo/odoo/blob/c7c68bab842aba5300f3a9deec28df6e17b40559/addons/stock/models/stock_picking.py#L645

and I studied the code some time ago and there's only one possibility of not being filled, and it's due to corrupted data (but not on normal flows).

**Comment by alexis-via** [comment]
I confirm this very important bug. I've been badly hit by this on a migration of a medical project with a majority of products are tracked by lots.
For done moves, it's just not possible to read the lot from the field reserved_quant_id on stock.move.operation.link, which is what the code of post-migration.py currently does.
I'll continue to work on this in the coming hours/days and post more info as I get them.

**Comment by alexis-via** [comment]
Using the field 'reserved_quant_id' from stock.move.operation.link to set lot_id on stock.move.line is a big mistake:

1) if you look at the definition of the field 'reserved_quant_id' on stock.move.operation.link https://github.com/odoo/odoo/blob/10.0/addons/stock/models/stock_pack_operation.py#L325 the help message says "Used at the stock_move_obj.action_done() time to avoid seeking a matching quant again". The help message is WRONG, the field 'reserved_quant_id' is NOT USED ANYWHERE in stock/models/stock_move.py, not in action_done() and not in any method !!!
2) the ONLY place in the 'stock' module that uses the field 'reserved_quant_id' of stock.move.operation.link is here: https://github.com/odoo/odoo/blob/10.0/addons/stock/models/stock_picking.py#L645
3) it is very easy to have a stock.pack.operation.link linked to a done move with reserved_quant_id=False: use a product tracked by lot and, on the stock pack operation, select another lot that the one which was booked by Odoo.

My conclusion: we should NOT use 'reserved_quant_id' from stock.move.operation.link to create stock.move.lines for done moves.

**Comment by alexis-via** [comment]
I've been working today on a solution to solve this issue. By the way, I also found an error in the migration script on 'mrp' about the lots (a small/easy error... which can have big consequences). I'll make a PR in the coming days.

**Comment by alexis-via** [comment]
FYI, there was no real bug in mrp module, the problem in mrp was apparently in my data (I don't know why...), so I fixed my data.

**Comment by alexis-via** [comment]
Here are some simple steps to create stock.move.operation.link with reserved_quant_id=False:
- create a new DB with the "stock" module
- on the stock settings page, enable "tracking by lot" 
- create a new stockable product with tracking by lot.
-  Click on "Update qty on hand" and create LOTA with qty 5
- Click again on "Update qty on hand" and create LOTB with qty 5
- create a new outgoing picking with the product with qty 1 and confirm it.
- The picking should become available (because there is enough stock) and it will create a stock.pack.operation with LOTA.
- edit the stock pack operation, set lot to LOTB and "Done Qty" to 1. Validate the picking.
=> the stock.pack.operation.link linked to the stock.move of the picking has **reserved_quant_id=False** and qty = 1.

Conclusion: the migration script for v10 to v11 will fail to keep lot tracability on all pickings where the user didn't pick the lot that was reserved by Odoo!!!

**Comment by alexis-via** [comment]
As spotted by @pedrobaeza , if you play the above scenario in v8, reserved_quant_id will have a value on stock.pack.operation.link.

**Comment by pedrobaeza** [comment]
Covered in #3451
