### ISSUE TITLE
[11.0 -> 12.0] Suggested SQL for base migration

### ISSUE THREAD

**Issue by steync027** [OCA/OpenUpgrade#2183]
**Impacted versions:**
11.0 -> 12.0

**Current behavior:**
Upgrade from 11.0 to 12.0. There are two issues:
1) Users cannot log in
2) Server actions no longer work

**Expected behavior:**
1) Users should be able to log in just fine
2) Server actions should still work

**Suggestion:**
1) UPDATE res_users SET password=password_crypt WHERE password IS NULL;
2) UPDATE ir_act_server SET code=REPLACE(code, 'object', 'record') WHERE code IS NOT NULL;

**Rationale:**
1) `auth_crypt` was merged into `base`. After migration, the login will no longer check if the `password_crypt` field is correct. Instead the `password` field is used during the login check.
2) Server actions no longer have the `object` keyword. Instead there is `records` and `record`. Most of the configuration will be fine with just replacing `object` with `record`.

**Comment by pedrobaeza** [comment]
This is something that is working for all. I think the merge was done in v11, not in v12. Why is a problem for you? Maybe a bad previous migration?

**Comment by steync027** [comment]
@pedrobaeza thanks for the feedback. I see now that 1) is addressed here:

https://github.com/OCA/OpenUpgrade/blob/12.0/odoo/addons/base/migrations/12.0.1.3/end-migration.py#L114-L121

However I'm not finding 2) where the server actions have changed. Can you recall where in the code this happens?

**Comment by pedrobaeza** [comment]
Server actions are not changed in the migration for now. I thinkthere's a risk of not converting them correctly. You must change them manually. I'm not affected by that because I hate to model things through manual server actions in the DB. I do everything in modules (so when I migrate the module code, I transform what needed), and server actions is not my preferred way of implementing things.

However, if you think that is possible to auto-transform them, please propose a PR with the change.

Closing this as answered.
