### ISSUE TITLE
Account 

### ISSUE THREAD

**Issue by cameroun** [OCA/OpenUpgrade#2189]
**Impacted versions: 11.0**

Steps to reproduce:
Using a Database with 10.000.000 account taxes, trying to openupgrade it from 10.0 to 11.0. During script migration, in account migration script, the process is very slow.
After a week, the script is still not finished and remains blocked with this log line. That is quite annoying.

```bash
2020-01-28 04:18:00,916 8292 INFO PROD odoo.modules.registry: module account: creating or updating database tables
2020-01-28 04:18:01,503 8292 INFO PROD odoo.models: Computing parent left and right for table account_group...
2020-01-28 04:38:12,780 8292 INFO PROD odoo.addons.auth_crypt.models.res_users: Hashing passwords, may be slow for databases with many users...
2020-01-28 04:38:52,098 8292 INFO PROD odoo.models: Storing computed values of account.invoice.activity_date_deadline
2020-01-28 04:39:22,448 8292 INFO PROD odoo.models: Storing computed values of account.invoice.tax.base
2020-01-28 04:40:32,802 8292 INFO PROD odoo.models: Storing computed values of account.partial.reconcile.max_date
2020-01-28 04:42:00,119 8292 INFO PROD odoo.models: Actual recompute of field account.invoice.tax.base for 10170740 recs.
```

The server is dedicated for the migration with a not so bad hardware :

RAM : 16 GO
HD : SSD
Processor : Intel(R) Core(TM) i5-6200U CPU @ 2.30GHz
No of Cores: 4

**What I tried**

Set a higher value for shared_buffers value in the ./postgresql.conf file. (128 MB -> 10 GO) --> Bad result. (longer process)
Set a higher value for limit_memory_hard et limit_memory_soft. (~600MB -> 10 GO) --> no result.

**Odoo settings : (quite simple)**
multi company. (~800)
Database size: ~500Go

Do you have some ideas for optimizations ? I'm ready to work on that but I'm not a quant expert, so any advice is welcome.
CC : @pedrobaeza, @StefanRijnhart.

Did you faced duration problems with databases with similar size ?

**Comment by StefanRijnhart** [comment]
Yes, we face performance problems and they lead to fixes in OpenUpgrade. Most scripts will not yet have had that treatment and have been developed functionally rather than optimized for performance.

All stored computed fields that are added in new versions of Odoo are a problem. The ORM is terrible in computing field values for large amounts of records. To fix this for a specific field whenever we migrate a database for which it is a problem we typically create the database column in the pre-migration script (which prevents the ORM from computing its value for all the records). We then make sure, either in the pre or the post script that the column is filled in a more performant way. Such performance fixes find their way into the code regularly. Would you be able to provide it for this case?

**Comment by pedrobaeza** [comment]
Closing this as no issue, but improvement. PRs are welcome for improving performance.

**Comment by cameroun** [comment]
Thank you @StefanRijnhart 

I followed your recommendations and created a function in the pre-migration file which adds the calculated field. The migration script no longer blocks at this stage, thank you.

But currently, I am facing the script for calculating order lines with multiple taxes. There are over 20 million invoice lines and [each loop in this](https://github.com/OCA/OpenUpgrade/blob/11.0/addons/account/migrations/11.0.1.1/post-migration.py#L94) script takes an average of 5 seconds.
```python
    for line in rest_lines:
        # avoid error on taxes with other type of computation ('code' for
        # example, provided by module `account_tax_python`). We will need to
        # add the computation on the corresponding module post-migration.
        types = ['percent', 'fixed', 'group', 'division']
        if any(x.amount_type not in types for x in line.invoice_line_tax_ids):
            continue
        # This has been extracted from `_compute_price` method
        currency = line.invoice_id and line.invoice_id.currency_id or None
        price = line.price_unit * (1 - (line.discount or 0.0) / 100.0)
        taxes = line.invoice_line_tax_ids.compute_all(
            price, currency, line.quantity, product=line.product_id,
            partner=line.invoice_id.partner_id,
        )
        line.price_total = taxes['total_included']
```
Can anyone help me turn this into SQL?

@pedrobaeza After these modifications and once I have a script that works with millions of invoice lines, I will do a PR.

Thank you in advance for your help.

**Comment by gary-no-1** [comment]
> Thank you @StefanRijnhart
> 
> I followed your recommendations and created a function in the pre-migration file which adds the calculated field. The migration script no longer blocks at this stage, thank you.
> 
> But currently, I am facing the script for calculating order lines with multiple taxes. There are over 20 million invoice lines and [each loop in this](https://github.com/OCA/OpenUpgrade/blob/11.0/addons/account/migrations/11.0.1.1/post-migration.py#L94) script takes an average of 5 seconds.
> 
> ```python
>     for line in rest_lines:
>         # avoid error on taxes with other type of computation ('code' for
>         # example, provided by module `account_tax_python`). We will need to
>         # add the computation on the corresponding module post-migration.
>         types = ['percent', 'fixed', 'group', 'division']
>         if any(x.amount_type not in types for x in line.invoice_line_tax_ids):
>             continue
>         # This has been extracted from `_compute_price` method
>         currency = line.invoice_id and line.invoice_id.currency_id or None
>         price = line.price_unit * (1 - (line.discount or 0.0) / 100.0)
>         taxes = line.invoice_line_tax_ids.compute_all(
>             price, currency, line.quantity, product=line.product_id,
>             partner=line.invoice_id.partner_id,
>         )
>         line.price_total = taxes['total_included']
> ```
> 
> Can anyone help me turn this into SQL?
> 
> @pedrobaeza After these modifications and once I have a script that works with millions of invoice lines, I will do a PR.
> 
> Thank you in advance for your help.

cannot write sql till code for compute_all is known.

**Comment by StefanRijnhart** [comment]
What you see in this script is that it has provided for an SQL method to cover what it thinks is the largest part of the invoice lines. Do you have 20 million lines that do not fall under this category of `simple_lines`? In that case, try and determine what the largest chunk is that you can cover with a relatively simple SQL method so those can be excluded from `rest_lines` (maybe you will only come up with code that is only valid for your installation, which does not qualify for inclusion in this project but that is alright). 

One thing that can be improved in our code is to invalidate the cache before `rest_lines` are processed, so that if a large part of your lines is actually excluded from rest_lines already they do not drag down the performance of processing those remaining lines.

**Comment by cameroun** [comment]
@StefanRijnhart I have over 13 million lines in the `rest_lines` category. I also tried to invalidate the cache before `res_lines`. 
```python
    env['account.invoice.line'].invalidate_cache()
    env['account.tax'].invalidate_cache()
    env['account.invoice'].invalidate_cache()
    rest_lines.invalidate_cache()

```
But I don't see any difference in performance.

**Comment by StefanRijnhart** [comment]
Yes, 13 million lines is a bit much so you'd have to resort to optimizing the recomputation for the shape of your data. Oh, I think invalidation is no longer necessary because the prefetch mechanism is on the RecordSet instead of the Environment.
