### ISSUE TITLE
Q: Repeat running migration scripts

### ISSUE THREAD

**Issue by dreispt** [OCA/OpenUpgrade#2404]
While working on migration scripts, I want to be able to fix things and retry running them.
The issue is that, if my previous `-u` run completed without errors, later updates to the module won't trigger the migration scripts again.

I worked around this tweaking the version check code, so that the migrations scripts are triggered if the current version is the same as the one to install (e.g. '12.0.1.0.1' -> '12.0.1.0.1').

I wonder if this makes sense, and If contributing this change can be helpful.

Thanks

**Comment by pedrobaeza** [comment]
It doesn't make sense, as migration scripts are not re-entrant (and you'll get other errors derived from this), and if the version has changed is because the whole module has been updated (there's a commit at the end). You need to restore a database before the module migration if you are iterating over the same migration script for debugging/refining it.

Doing migration scripts re-entrant adds a lot of added code complexity (a lot of checks for seeing if the works have been done) for no significant gain in real environments.
