### ISSUE TITLE
[RFC] changing the format of the analysis files

### ISSUE THREAD

**Issue by legalsylvain** [OCA/OpenUpgrade#2477]
Following @Yajo [comment](https://github.com/legalsylvain/openupgrade-framework/pull/4#discussion_r537367996), it could be more convenient to have another format for the analysis file. 

### Current : 

1) an ``upgrade_analysis.txt`` log file is generated by ``upgrade_analysis`` module (server-tools repository) previously ``openupgrade_records``.

### sample for V14 base analysis : 

```
 ---Models in module 'base'---
model base.document.layout (moved to web) [transient]
new model ir.qweb.field.image_url [abstract]
new model res.users.apikeys [sql_view]
[...]
---Fields in module 'base'---
base         / ir.model                 / order (char)                  : NEW required, req_default: function, hasdefault
base         / ir.model.data            / date_init (datetime)          : DEL
base         / ir.model.data            / date_update (datetime)        : DEL
[...]
---XML records in module 'base'---
NEW ir.actions.act_window: base.action_apikeys_admin
NEW ir.actions.act_window: base.action_res_users_keys_description
DEL ir.actions.act_window: base.action_base_document_layout_configurator [renamed to web module]
```

2) Openupgrader copies the file and rename it into ``upgrade_analysis_work.txt`` and add extra comment, add the migration scripts and commit all the diff.

### Possible other formats : 

A) YAML
B) json
C) csv
D) ... other ?

my PoV : 

I'm not sure that yaml or json are good candidate because it will generate bigger file. (an existing line will be converted in several lines (or maybe I missed something ?))
However, csv file will be maybe better displayed on github interface ([see](https://github.com/OCA/OpenUpgrade/blob/13.0/addons/analytic/security/ir.model.access.csv)). So maybe it could be better...

I don't plan to work on this subject, this issue is just there as a reminder.

**Comment by yajo** [comment]
I proposed YAML originally because it is easy to read by humans, easy to parse by machines, and allows to insert comments, which I think is an important topic.

CSV, OTOH, when properly rendered, is easy to read and parse also. Regarding comments, it can be solved by just adding a "comments" column to any tables that it creates. It could be a good candidate. Although one thing is true: this file doesn't just contain 1 single resource, like usually csv tables. It contains details about records, views, fields, constraints, and possibly more stuff. I'm not sure a 2D array is the best choice to represent such structure. :thinking:

**Comment by ajepe** [comment]
I vote for json or yaml, where can I see documentation of newly refactor openupgrade

**Comment by pedrobaeza** [comment]
This is still relevant. I think the format can be XML or JSON.

**Comment by rvalyi** [comment]
hello, I share some thoughts: along with the difference analysis file, in the future, we could also consider dumping some kind of json representing the current datamodel, and possibly the module dependency graph as given by manifestoo.

Indeed, in the coming years, chances are that by doing "fined tuned" training on AI like GPT3 with historical pairs from the Openupgrade migration scripts from the previous years such as (diff+structure, migrations scripts) we might eventually be able to generate a large part of the migration scripts. Of course it would never generate complex migrations, but if it could generate a large part of the easiest 50% for us to review, that may still be a big win, no? Indeed chatGPT has already some good Odoo module "knowledge" and it might soon be able to help for this. I might be wrong but I think the current data structure might help the AI just as much as the diff analysis file, especially because it may not know the exact current Odoo datamodel (apparently chatGPT is trained on Odoo v14 for instance but not v16).

see https://platform.openai.com/docs/guides/fine-tuning

**Comment by pedrobaeza** [comment]
There can be some help indeed from AI, although some fields renamings are arbitrary and not easily guessed. The problem here may be to train the model.

**Comment by rvalyi** [comment]
I'm not sure how much it could help an AI, but eventually we might also be able to extract the commits/diff leading to the datamodel change of a module between 2 versions. Referencing these commits/PRs might also help human contributors...

Again just an idea, as extracting the relevant commits might not be too trivial either. We could also feed the AI with the Odoo release note, but as it's not an input/output pair, I'm not sure what it could "learn" from it.

probably not useful in the next year but may be possible in 2-3 years...

**Comment by legalsylvain** [comment]
Hi. The original topic is about the format. The current format is not very easy to be parsed. XML and Json are better.
but I think that the IA considerations are unrelated. I don't think that openai will understand better xml / json / or current format. (Result will be the same in all cases)

Regarding the original topic : 

I don't see any interest at the moment to change the format, but maybe I'm wrong and I'm open to this kind of change. (not blocking)

Could people who are motivated by a change (xml / yaml / json) write on this issue some implementation examples (with the "_work" version). It will help to select the best format.

Thanks !

**Comment by rvalyi** [comment]
well I commented about the opportunity to complete the analysis "input" in the AI prospective because if we try to complete it with the current data structure at some point, I'm pretty sure a structured format such as json or yaml would be a better fit to represent the modules classes and their fields (or pure Python eventually). And as the historical training set would be very important to train an AI, the sooner we get it right, the better. But in any case it could be different extra files and we could also add them later on for past migrations, just mentioning the idea.

**Comment by yajo** [comment]
I'm not oposed to that hypothetical future AI doing the migration scripts, but I think the strongest reasons to use a parseable format are:

1. Some logic can be generated for the docs, so they better reflect the reality of current migration status.
2. Some "magic" openupgradelib method that parses that input and does the rutinary stuff: `openupgrade.generate_pre_migration_for_spec(Path("module" / "migration-spec.yaml"))`
