### ISSUE TITLE
[RFC] Feedback on New V14 design

### ISSUE THREAD

**Issue by legalsylvain** [OCA/OpenUpgrade#2711]
Hi all, and specially @RaulOForgeFlow

First, thanks for contributing in V14 openUpgrade. (lot of PR to review ! https://github.com/OCA/OpenUpgrade/pulls?q=is%3Aopen+is%3Apr+author%3ARaulOForgeFlow+milestone%3A14.0)

I'd like to have your feed back regarding the new design of Openupgrade following recent refactoring.
Did you faced some issues  or some limitation with that new "module design"  that replaces the previous "fork design" ? 
Do you see some improvement to do ? 
Do you think documentation is OK for new comers ? 

thanks for your feedback.

**Comment by pedrobaeza** [comment]
Yeah, take into account that this is part of the OCA funded project for having v14 migration scripts, and Raúl is the designed person for doing the initial kick-off. The new process hasn't been yet really tested because the CI is not working with new version (ping @MiquelRForgeFlow :stuck_out_tongue_closed_eyes:), and that's something pending from our side, and then, real scenario migrations. I think it's soon to say about it.

**Comment by pedrobaeza** [comment]
All working properly with the new design, so closing.
