### ISSUE TITLE
set_defaults write values with ORM instead of SQL

### ISSUE THREAD

**Issue by pedrobaeza** [OCA/OpenUpgrade#328]
I'm having very slow performance when migrating a DB with a lot of partners and I ended up finding that this method is the guilty of that.

@StefanRijnhart, I think you wrote this one. Is there any reason to use ORM in it instead of SQL?

**Comment by StefanRijnhart** [comment]
What are the reasons to use the ORM instead of SQL in regular Odoo code?

We see a trend to move ORM functionality towards SQL in OpenUpgrade. Of course it is more performant, but replacing ORM API with SQL is frowned upon in regular Odoo code for all the know reasons (security and triggers). The latter argument is of course valid for OpenUpgrade as well.

**Comment by pedrobaeza** [comment]
Well, in this case is very useless to do it that way, and can lead to situations like the one I have just right now in one DB: tracing, I have found that writing one of the IDs, the process hangs without reason. Probably it's a bug in the code, but reached via ORM. Seeing the use of most of the set_defaults calls, there's no problem in doing it via SQL.

If you agree, I can make a PR adding a keyword argument `use_orm=False` and keep the current logic when this argument is True, and default to an SQL update.

**Comment by StefanRijnhart** [comment]
Your approach sounds fine, go ahead.

**Comment by pedrobaeza** [comment]
Done on #340
