### ISSUE TITLE
Infrastructure migration to 16.0

### ISSUE THREAD

**Issue by StefanRijnhart** [OCA/OpenUpgrade#3580]
- [x] Create 16.0 branch
- [x] Migrate `upgrade_analysis` (@StefanRijnhart https://github.com/OCA/server-tools/pull/2417)
- [x] Populate `openupgrade_scripts` with initial analysis (@StefanRijnhart -  - https://github.com/OCA/OpenUpgrade/pull/3583)
- [ ] Migrate openupgrade_framework

**Comment by legalsylvain** [comment]
Thanks. Please ping me when you need review.

**Comment by Maralai** [comment]
I would love to know how I can help. I have heard that it would take 1 month to upgrade to 15 > 16 in the enterprise edition. I just somehow do not believe it would take that long and would sooner do it myself. 

From my perspective If I were tasked with managing this import so that I may execute it continuously and on demand, I would imagine it would involve the following steps, where left is 15 and right is 16. 

- [ ] Reviewing the change log with respect to ORM, know what changed ahead of time.
- [ ] Comparing tables from one version to the other for each model that has records on the left.
- [ ] Create a table representing the map between field names, and if required table names between versions.
- [ ] Write a method abstracting the updates so that it is table/field independent.
- [ ] Write a method to iterate over the left writing to the right.

What are your thoughts? Does this help? What would you change or intend to do?

I have a use case to do this work myself. My concern is that I may not abstract it enough to be applicable to others without understanding the prior approaches and previous versions' timelines. Surely a company like Odoo intends to get it from 30 days down to a weekend, how do they? Or why can't they? Or was the timeframe I was quoted way off?

**Comment by pedrobaeza** [comment]
All that work is already done. Comparison is done through https://github.com/OCA/server-tools/tree/16.0/upgrade_analysis, and differences are logged in #3583

**Comment by bnisevic** [comment]
How can I help to push this forward?

**Comment by kalungia** [comment]
Hello, has anyone been able to do migration from V15 to V16

**Comment by neoneddy** [comment]
@kalungia is asking the real questions.  I'm curious as well.

**Comment by pedrobaeza** [comment]
That's not possible, as there's no migration scripts.

**Comment by neoneddy** [comment]
@pedrobaeza I know this is out of scope, but what would b your recommendation for someone like me on Odoo CE 15.  No customizations. ?

**Comment by pedrobaeza** [comment]
I don't get your question.

**Comment by neoneddy** [comment]
@pedrobaeza I’m currently on Odoo 15 community edition.   I have not done any customizations, it’s completely stock.

what would be the best way for me to upgrade to Odoo 16?

**Comment by pedrobaeza** [comment]
Already answered 2 comments ago.

**Comment by legalsylvain** [comment]
Closing. Looks done. Feel free to reopen if you're not agree.
