### ISSUE TITLE
Is it possible to migrate only a few modules to other version instead to upgrade the complete database?

### ISSUE THREAD

**Issue by fedexin40** [OCA/OpenUpgrade#377]
Hi all 
I was wondering for example the next situation.
I have a database created in openerp V7 and y wanted to migrate to openerp V8 only a few modules for exmaple stock, mrp, delivery. But i would like to keep the rest of the database whitout changes. 
 Could be possible maybe from OpenUpgrade branch 8.0 execute --upgrade stock  or similar?
@ all or in your opinion what could be the best way to do that?

Regards

**Comment by pedrobaeza** [comment]
Well, this is not what is intended with OpenUpgrade, and I can't figure out a use case for such thing, but in theory you can upgrade only some module with -u/--update <module>. For sure it will fail, due to migration scripts are developed expecting to have the dependencies migrated. You also will have for sure problem if you want to backport these modules because of the data layout.

**Comment by fedexin40** [comment]
okay Thanks @pedrobaeza :)
