### ISSUE TITLE
[analysis] Removed models are not logged per module

### ISSUE THREAD

**Issue by JordiBForgeFlow** [OCA/OpenUpgrade#468]
For example, account.analytic.journal disappears in v9, and there's no trace of this in the analysis files, except for many2one references to this model that are deleted.

**Comment by StefanRijnhart** [comment]
They are logged in the general log: https://github.com/OCA/OpenUpgrade/blob/9.0/openerp/addons/base/migrations/9.0.1.3/openupgrade_general_log.txt#L77

It is hard to log them by module, because Odoo does not properly register which module 'owns' a model, although we could log a module in every module in which it is either defined or overridden as this corresponds to the model_ entries in ir_model_data.

**Comment by pedrobaeza** [comment]
Yeah, I think that can be an improvement, although it's very verbose. We can also use a reference count to determine which module is the base (or maybe through _inherit/_name property - the original module that declares the model for the first time is the one that doesn't have _inherit).

**Comment by pedrobaeza** [comment]
@mreficent a challenge for you :wink:

**Comment by MiquelRForgeFlow** [comment]
Each model has the `_original_module` attribute, which shows the module where the model is declared for first time.

**Comment by pedrobaeza** [comment]
OK, if it works properly, then we have the solution!

**Comment by MiquelRForgeFlow** [comment]
With https://github.com/OCA/OpenUpgrade/pull/2004 and https://github.com/OCA/OpenUpgrade/pull/2012 merged, I think we can close this issue.
