### ISSUE TITLE
Useless selection of upgradeable addons in Travis

### ISSUE THREAD

**Issue by StefanRijnhart** [OCA/OpenUpgrade#521]
The selection in https://github.com/OCA/OpenUpgrade/blob/9.0/.travis.yml#L44 is useless, because as soon as you upgrade base, all the modules that depend on it (i.e. all modules) will be marked for upgrade as well. Sometimes the upgrade just marches on even on the non covered modules, but even then the tests take much longer than necessary.

Should we change this semantics in Odoo itself so that the implicit selection in the dependency hierarchy is not applied? Maybe governed by the OPENUPGRADE_TESTS environment variable?

**Comment by pedrobaeza** [comment]
If it can be done, I vote for that partial testing.

**Comment by hbrunn** [comment]
The selection has its merits because of https://github.com/OCA/OpenUpgrade/blob/9.0/.travis.yml#L47, where we set modules not marked as migrated as uninstalled.

I don't think we should change such fundamental mechanisms if not absolutely necessary, and the inconvenience of waiting longer for test results doesn't qualify for me.

**Comment by StefanRijnhart** [comment]
I see, I missed that when I was trying to fix tests locally on https://github.com/OCA/OpenUpgrade/pull/120. We'll have to see how that pans out in practice. Thanks for the clarification!
