### ISSUE TITLE
deleting moves of special periods

### ISSUE THREAD

**Issue by hbrunn** [OCA/OpenUpgrade#759]
In https://github.com/OCA/OpenUpgrade/blob/9.0/addons/account/migrations/9.0.1.1/pre-migration.py#L86, we delete all moves and lines of special periods which are not in the first special period. I think this is wrong, as we lose all financial corrections made when closing a fiscal year.

@jbeficent could you elaborate your reasoning for deleting the other move lines and do you agree we rather need something like (pseudocode)

```python
for period in special_periods:
    next_normal_period = get_normal_period_after(period)
    move_all_lines_from_period_to_period(period, next_normal_period)
```

the change is simple enough to do, but before submitting I wanted to make sure there's no wrong reasoning on my side. I believe with the current migration, we get inconsistent databases as soon as there's a write-off or some other correction when closing a fiscal year.

If the above is true, I'll also provide a script that generates the missing moves and lines from an existing 8.0 database.

**Comment by JordiBForgeFlow** [comment]
@hbrunn IMHP the corrections made when closing a fiscal year should be posted must be posted in a normal period, not in the opening period. The opening period is supposed to be used only to handle the automated opening entries.

In my use case I have a separate script that moves the journals that are not created by automated opening entries to the next valid period, as you suggested. 

But the opening entries generated by Odoo are not valid journal entries, because they forward the outstanding balance of the previous year to the new year. If you keep them, you would end up with double the balance of each balane sheet account in the next year.

For example in Odoo 8, at the end of the year 2016 I have account 'Assets' with Debit balance of 1000.
When I create the opening entries for 2016, Odoo will create a opening entry containing 'Assets' and debit 1000.

If you then migrate to Odoo 9 and do not get rid of the opening journal entry, you will have the journals for 2016, ending with a debit balance of 1000 + a journal entry in 2017 with an additional debit of 1000. Thus the balance of this account as of january 2017 will be 2000.

**Comment by hbrunn** [comment]
thanks for the explanation. I've not been specific enough, indeed I meant only the manually created ones. Can we integrate your script somehow into account's migration scripts? Probably you use some trick to differentiate the manually created entries from the automatic ones (I'm curious how you do this), then we should do the same in the migration. As there's nothing in the former versions that forces people not to create manual entries in special periods, we need to support this case I think.

**Comment by JordiBForgeFlow** [comment]
`
def move_normal_moves_from_special_periods(conn, cr):
    """The account migration script will delete all moves that are in the
    special periods. We need to remove any moves that are not created as
    opening balances for the opening period, so that they are not deleted."""

    print("""Selecting all the account moves that are in special periods,
    but not in a centralized journal.""")
    try:
        cr.execute("""
            SELECT am.id, am.name
            FROM account_move AS am
            INNER JOIN account_period AS ap
            ON ap.id = am.period_id
            INNER JOIN account_journal AS aj
            ON aj.id = am.journal_id
            WHERE ap.special=True
            AND aj.code NOT IN ('FY', 'OC11')
        """)
    except Exception as e:
        print e.message
        conn.rollback()
        return
    conn.commit()

    move_ids = []
    for move_id, move_name in cr.fetchall():
        move_ids.append(move_id)
        print("""Move %s will be moved to another period""" % (move_name,))

    if move_ids:
        print("""Updating all previously selected moves to a new non special
        period within the move date.""")
        try:
            cr.execute("""
                UPDATE account_move as am
                SET period_id = ap.id
                FROM account_period AS ap
                WHERE am.id in %s
                AND ap.date_start <= am.date
                AND ap.date_stop >= am.date
                AND ap.special = False
            """, (tuple(move_ids),))
        except Exception as e:
            print e.message
            conn.rollback()
            return
        conn.commit()`

**Comment by hbrunn** [comment]
hmmm, your codes are database specific of course. I'll try to find some more general heuristics based on the journals used

**Comment by JordiBForgeFlow** [comment]
Perhaps selecting journals that do not have the 'centralization' set?

**Comment by hbrunn** [comment]
I wanted to check back with the accountant of the customer, and for them, this works. Done in #768
