### ISSUE TITLE
Error in a CRM request

### ISSUE THREAD

**Issue by charle-s** [OCA/OpenUpgrade#771]
Hi, 

First, I am very impressed in your projet. Thanks ! 👍 

However i got a probleme durindg the CRM migration from 8 to 9 :
In a file "addons/crm/migrations/9.0.1.0/pre-migration.py" on line 92, the request "ALTER TABLE IF EXISTS crm_lead_lost_reason RENAME TO crm_los[...]" looks wrong. I think that is note possible to associate "IF EXISTS" with "RENAME TO".
Am I right or not ?

Thanks in advance

**Comment by hbrunn** [comment]
this was introduced with postgres 9.2: https://www.postgresql.org/docs/9.2/static/sql-altertable.html
And you really don't want to run an older postgres, there's so much improvements that I don't think we should make an effort to support older versions.
I'll keep this issue open to ask @OCA/openupgrade-maintainers about their opinion which is the least version we should support

**Comment by charle-s** [comment]
Thanks for you reactivity.
I didn't ask you to do an effort to support older versions of postgres, don't worry.
Have a good day

**Comment by charle-s** [comment]
Hi, 
i got the version 9.4 of Postgres and it works better. But i have an other problem : 
IntegrityError: insert or update on table "res_country" violates foreign key constraint "res_country_currency_id_fkey"
DETAIL:  Key (currency_id)=(1) is not present in table "res_currency".

Do you know how i can resolv it ? I search on forum but i didn't find something

Thanks in advance

**Comment by charle-s** [comment]
Hi,
Someone know a solution for my problem ? 
Thanks in advance

**Comment by hbrunn** [comment]
you should post the full backtrace from the log. otherwise, it's annoying guesswork to try to help you in which case most people including me prefer to use their time in a more rewarding manner.
that said, usually, this kind of error points to some record expected but not available because it was deleted manually. if that's the case, running the original 8.0 server with parameter --update=all will recreate those records

**Comment by pedrobaeza** [comment]
Closing as no response
